$(document).ready(function(){jQuery.fn.exists=function(){return this.length>0;}
shake();if(window.DeviceOrientationEvent){$('.cell-image').css('transition-duration','0.05').css('-webkit-transition-duration','0.05').css('-webkit-transition-timing-function','linear');window.addEventListener('deviceorientation',function(eventData){var tiltLR=eventData.gamma;var tiltFB=eventData.beta;var dir=eventData.alpha
var motUD=null;deviceOrientationHandler(tiltLR,tiltFB,dir,motUD);},false);}
var PrevX=0;function deviceOrientationHandler(tiltLR,tiltFB,dir,motUD){if(Math.abs(tiltLR-PrevX)>=1){if(window.orientation==0){$deg=(tiltLR/2)*-1;$('.cell-image').css('-webkit-transform','rotate('+$deg+'deg)');PrevX=tiltLR;}else{if(window.orientation==180){$deg=(tiltLR/2);$('.cell-image').css('-webkit-transform','rotate('+$deg+'deg)');PrevX=tiltLR;}else{$('.cell-image').attr('style','');}}}}
function shake(){$('.cell-image').transition({rotate:'-10deg'},200,'in-out');$('.cell-image').transition({rotate:'10deg'},200,'in-out');$('.cell-image').transition({rotate:'-10deg'},200,'in-out');$('.cell-image').transition({rotate:'10deg'},300,'in-out');$('.cell-image').transition({rotate:'-5deg'},300,'in-out');$('.cell-image').transition({rotate:'2deg'},300,'in-out');$('.cell-image').transition({rotate:'0deg'},300,'in-out',function(){$('.cell-image').attr('style','');});}
if($("#header .balance").exists()&&Modernizr.cssanimations&&Modernizr.csstransitions){setTimeout(function(){$("#header .balance-1").addClass('animated');},300);$("#header .balance-1").bind("webkitAnimationEnd oAnimationEnd msAnimationEnd animationend",function(){$('.balance-1').transition({rotate:'-7deg'},3000,'in-out',function(){$("#header .balance-1").addClass("oscillate");});});$("#header .balance-2").bind("webkitAnimationEnd oAnimationEnd msAnimationEnd animationend",function(){$('.balance-2').transition({rotate:'7deg'},3000,'in-out',function(){$("#header .balance-2").addClass("oscillate");});});}
if($('.login').exists()){$('#header .login-form').hide();$('#header .btn-login').click(function(){$('#header .login-form').slideDown();$(this).parent().addClass("selected");return false;});$('html').click(function(){$('#header .login-form').slideUp();$('.login').removeClass("selected");});$('#header .login-form').click(function(event){event.stopPropagation();});$('#header .login-form .btn-close').click(function(){$('#header .login-form').slideUp();$('.login').removeClass("selected");return false;})}
if($(".gallery-overflow").exists()){var resizeOverflow=function(){var parentWidth=$(".gallery-overflow").parent().width(),windowWidth=$(window).width();$(".gallery-overflow").css({width:windowWidth,left:-(windowWidth-parentWidth)/2});};$(window).resize(resizeOverflow);resizeOverflow();}
if($('.scrolltoanchor').exists()){$(".scrolltoanchor").click(function(){$.scrollTo($($(this).attr("href")),{duration:650});return false;});}
$(window).scroll(function(){$("#portfolio,#evi,#prijzen").each(function(){if($(window).scrollTop()>($(this).offset().top-100)&&$(window).scrollTop()<=($(this).offset().top+$(this).outerHeight(true))){$(this).find(".main-nav").fadeIn();}
else{$(this).find(".main-nav").fadeOut();}});});if($("#gallery-block-wrapper").exists()){var loadLightboxImage=function($el){$("#main .info .gallery-list li").removeClass("active");$el.addClass("active");var href=$el.find("a").attr("href");$(".lightbox .tbl-cell img").attr("src",href);},slideBlock=function(index){if(index>=0&&index<$("#gallery-block-wrapper > ul > li").size()){$("#gallery-block .paging li").removeClass("active").eq(index).addClass("active");$("#gallery-block-wrapper > ul > li").removeClass("active").eq(index).addClass("active");$("#gallery-block-wrapper > ul").animate({left:-$("#gallery-block-wrapper > ul > li:first").width()*index});}},printpager=function(){var html="";var count=$("#gallery-block-wrapper > ul > li").size();for(var i=0;i<count;++i){html+='<li'+((i===0)?' class="active"':'')+'><a href="#">'+(i+1)+'</a></li>';}
$("#gallery-block .paging").html(html);};$("#main .info .box .list a").bind("click",function(e){e.preventDefault();var href=$(this).attr("href");$.ajax({url:'/inc/ajax.inc.php',type:'post',data:{action:'getGalleryData',id:href},complete:function(xhr,textStatus){console.log('complete');},success:function(data,textStatus,xhr){openGallery(data);},error:function(xhr,textStatus,errorThrown){console.log(errorThrown);}});});$("#gallery-block .btn-close").bind("click",function(e){$("#gallery-block").animate({left:"200%"},1000);$('#gallery-block-wrapper').html('');e.preventDefault();});}
function openGallery(html){$("#gallery-block-wrapper").html(html);$('.fancybox').fancybox();$('.fancybox').fancybox({'nextEffect':'fade','prevEffect':'fade','margin':50,'afterShow':function(){$(".fancybox-wrap, .fancybox-img").touchSwipeRight(function(direction){$.fancybox.prev();});$(".fancybox-wrap, .fancybox-img").touchSwipeLeft(function(direction){$.fancybox.next();});},'afterClose':function(){$(".fancybox-wrap, .fancybox-img").unbindSwipe();}});slideBlock(0);$("#gallery-block").animate({left:"50%"},1000,function(){printpager();$("#gallery-block-wrapper").find(" > ul").width($("#gallery-block-wrapper > ul > li:first").width()*$("#gallery-block-wrapper > ul > li").size());$("#gallery-block .next,#gallery-block .prev").unbind("click").bind("click",function(e){var index=$("#gallery-block .paging li.active").index();if($(this).hasClass("prev")){--index;}
else{++index;}
slideBlock(index);e.preventDefault();});$("#gallery-block .paging a").unbind("click").bind("click",function(e){var index=$(this).parent().index();slideBlock(index);e.preventDefault();});});}
if($("#main .gallery .circle div").exists()){if(Modernizr.cssanimations&&Modernizr.csstransitions){$(window).scroll(function(){if(($(window).scrollTop()-$("#main .gallery").offset().top)>=-100){$("#main .gallery-2").addClass("animated");setTimeout(function(){$("#main .gallery-3").addClass("animated");},1000);}});}
var slideBox=function(index){$("#main .gallery-1 .gallery-holder ul li").removeClass("active");$("#main .gallery-1 .gallery-holder ul li").eq(index).addClass("active");$("#main .gallery-1 .gallery-holder ul").animate({left:-$("#main .gallery-1 .gallery-holder li:first").width()*index},500);$("#main .gallery-1 .link-next,#main .gallery-1 .link-prev").removeClass("inactive");if(index===$("#main .gallery-1 .gallery-holder li").size()-1){$("#main .gallery-1 .link-next").addClass("inactive");}
else if(index===0){$("#main .gallery-1 .link-prev").addClass("inactive");}}
$("#main .gallery-1 .gallery-holder ul").width($("#main .gallery-1 .gallery-holder li").size()*$("#main .gallery-1 .gallery-holder li:first").width());if($("#main .gallery-1 .gallery-holder li").size()===1){$("#main .gallery-1 .link-next").addClass("inactive");}
$("#main .gallery-1 .link-prev,#main .gallery-1 .link-next").bind("click",function(e){var index=$("#main .gallery-1 .gallery-holder li.active").index();if($(this).hasClass("link-next")){++index;}
else{--index;}
slideBox(index);e.preventDefault();});setInterval(function(){$('#main .gallery .circle div').animate({rotate:'+=360deg'},20000,'linear');},20000);$('#main .gallery .circle div').animate({rotate:'+=360deg'},20000,'linear');}
setInterval(function(){if($('#bigstar').hasClass('black')){$('#bigstar').removeClass('black');$('#smallstar').removeClass('red');}else{$('#bigstar').addClass('black');$('#smallstar').addClass('red');}},1500);});function hideFormText(){var _inputs=document.getElementsByTagName('input');var _txt=document.getElementsByTagName('textarea');var _value=[];if(_inputs){for(var i=0;i<_inputs.length;i++){if(_inputs[i].type=='text'||_inputs[i].type=='password'){_inputs[i].index=i;_value[i]=_inputs[i].value;_inputs[i].onfocus=function(){if(this.value==_value[this.index])
this.value='';}
_inputs[i].onblur=function(){if(this.value=='')
this.value=_value[this.index];}}}}
if(_txt){for(var i=0;i<_txt.length;i++){_txt[i].index=i;_value['txt'+i]=_txt[i].value;_txt[i].onfocus=function(){if(this.value==_value['txt'+this.index])
this.value='';}
_txt[i].onblur=function(){if(this.value=='')
this.value=_value['txt'+this.index];}}}}
if(window.addEventListener)
window.addEventListener("load",hideFormText,false);else if(window.attachEvent)
window.attachEvent("onload",hideFormText);